### ISSUE TITLE
根据 page_manager 接口更新 map editor 

### ISSUE THREAD

**Issue by yangtau** [yangtau/feed-the-dragon#4]
## Task
- [x] 从 page_manager.PageBase 派生出 MapEditorPage
- [ ] 完善界面：地图名输入框，确认按钮等
- [ ] 地址信息更新到 resources/config/level.json 中
## Note
**首先把 ui 分支合并到 map_editor 分支:`git merge origin/ui`**

派生子类的实现可以参考[start_page](https://github.com/yangtau/feed-the-dragon/tree/ui/start_page.py)，[game_page](https://github.com/yangtau/feed-the-dragon/tree/ui/game_page.py)。

Button，TextInput 等控件可以考虑使用 pygame_gui.elements 中的组件。我已经完成了对 pygame_gui 的事件处理的一些封装，可以通过 PageBase 类的 regesiter_gui_event_handler 完成事件注册，使用方法可以参考 [start_page](https://github.com/yangtau/feed-the-dragon/tree/ui/start_page.py) 中的按钮使用方法。参考文档：[pygame_gui docs](https://pygame-gui.readthedocs.io/en/latest/quick_start.html)， [Input 事件](https://pygame-gui.readthedocs.io/en/latest/events.html#uitextentryline-ui-text-entry-finished)。

level.json 文件更新可以考虑在 resources/resource.py 中增加方法，避免直接读写文件。
